routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Pengguna;
use App\Http\Controllers\StuController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', 'Pengguna@index'); // udah gak bisa dipake

Route::get('/', [Pengguna::class, 'index']);

Route::get('/about', [Pengguna::class, 'about']);

Route::get('/pemakai', [Pengguna::class, 'pemakai']);

Route::resource('/stu', StuController::class);

Route::get('/sendmail', [MailController::class, 'sendEmail']);

app/Models/Stu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stu extends Model
{
    use HasFactory;

    protected $fillable = ['judul', 'penulis', 'teks'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Mail\testMail;
use Illuminate\Mail\Mailer;

class MailController extends Controller
{
    public function sendEmail(){
        $details = [
            'title' => 'Judul',
            'body' => "Testing send email with Laravel 8"
        ];
        Mail::to('1811503083@student.budiluhur.ac.id')->send(new testMail($details));
        return 'Email Berhasil Terkirim Lagi 2';
    }
}

app/Http/Controllers/Pengguna.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Pengguna extends Controller
{
    public function index() {
        $title = "Homepage | Official Latihan 1";
        $content = "Selamat Datang di Homepage";
        return view('index', [
            'title' => $title,
            'content' => $content
        ]);
    }

    public function about() {
        $title = "About | Official Latihan 1";
        $nama = "Rheks";
        $gambar = "favicon.jpg";

        return view('about', [
            'title' => $title,
            'nama' => $nama,
            'gambar' => $gambar
        ]);
    }

    public function pemakai() {
        $data = [
            [
                "title" => "Judul Pertama",
                "author" => "Penulis Pertama",
                "teks" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore amet dignissimos dolor 
                reprehenderit aliquid error impedit doloribus ipsam, facere similique, doloremque mollitia nemo? 
                Assumenda dolorem eaque id. Debitis neque in sapiente cumque, fugiat saepe autem atque ipsam accusamus
                ores consectetur a. Quasi qui vel assumenda dolorum vitae nostrum, in earum molestias iusto ipsum at 
                repudiandae atque perferendis, ut inventore. Similique veritatis consequuntur numquam? Ut reiciendis 
                perspiciatis non laboriosam corrupti explicabo illo cumque, error atque maiores. Corrupti voluptate 
                minus iusto accusamus."
            ],
            [
                "title" => "Judul Kedua",
                "author" => "Penulis Kedua",
                "teks" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore amet dignissimos dolor 
                reprehenderit aliquid error impedit doloribus ipsam, facere similique, doloremque mollitia nemo? 
                Assumenda dolorem eaque id. Debitis neque in sapiente cumque, fugiat saepe autem atque ipsam accusamus
                ores consectetur a. Quasi qui vel assumenda dolorum vitae nostrum, in earum molestias iusto ipsum at 
                repudiandae atque perferendis, ut inventore. Similique veritatis consequuntur numquam? Ut reiciendis 
                perspiciatis non laboriosam corrupti explicabo illo cumque, error atque maiores. Corrupti voluptate 
                minus iusto accusamus."
            ],
            [
                "title" => "Judul Ketiga",
                "author" => "Penulis Ketiga",
                "teks" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore amet dignissimos dolor 
                reprehenderit aliquid error impedit doloribus ipsam, facere similique, doloremque mollitia nemo? 
                Assumenda dolorem eaque id. Debitis neque in sapiente cumque, fugiat saepe autem atque ipsam accusamus
                ores consectetur a. Quasi qui vel assumenda dolorum vitae nostrum, in earum molestias iusto ipsum at 
                repudiandae atque perferendis, ut inventore. Similique veritatis consequuntur numquam? Ut reiciendis 
                perspiciatis non laboriosam corrupti explicabo illo cumque, error atque maiores. Corrupti voluptate 
                minus iusto accusamus."
            ]
        ];

        return view("pemakai", compact('data'));
    }
}

app/Http/Controllers/StuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Stu;

class StuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Stu::all();
        return view('stu.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stu.Create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul'=> 'required|size:3',
            'penulis'=> 'required',
            'teks'=> 'required'
        ]);

        Stu::create($request->all());

        return redirect()->route('stu.index')->with('status', 'Data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Stu $stu)
    {
        return view('stu.show', compact('stu'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Stu $stu)
    {
        return view('stu.edit', compact('stu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stu $stu)
    {
        $request->validate([
            'judul'=> 'required',
            'penulis'=> 'required',
            'teks'=> 'required'
        ]);

        $stu->update($request->all());

        return redirect()->route('stu.index')->with('status', 'Data berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stu $stu)
    {
        $stu->delete();

        return redirect()->route('stu.index')->with('status', 'Data berhasil dihapus');
    }
}

resources/views/about.blade.php
@extends('layouts.main')

@section('title', $title)

@section('container')
    <div class="container">
        <h3>{{ $nama }}</h3>
        <img src="img/{{ $gambar }}" width="30px" height="30px">
    </div>
@endsection

resources/views/contact.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 8 Contact Form</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg==" crossorigin="anonymous" />
</head>
<body>
    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-8 offset-2 mt-5">
                <div class="card">
                    <div class="card-header bg-info">
                        <h3 class="text-white">Laravel 8 Contact Form</h3>
                    </div>
                    <div class="card-body">
                        
                        @if(Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session::get('success') }}
                            @php
                                Session::forget('success');
                            @endphp
                        </div>
                        @endif

                        <form method="POST" action="{{ route('contact-form.store') }}">

                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Name:</strong>
                                        <input type="text" name="name" class="form-control" placeholder="Name" value="{{ old('name') }}">
                                        @if ($errors->has('name'))
                                            <span class="text-danger">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Email:</strong>
                                        <input type="text" name="email" class="form-control" placeholder="Email" value="{{ old('email') }}">
                                        @if ($errors->has('email'))
                                            <span class="text-danger">{{ $errors->first('email') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Phone:</strong>
                                        <input type="text" name="phone" class="form-control" placeholder="Phone" value="{{ old('phone') }}">
                                        @if ($errors->has('phone'))
                                            <span class="text-danger">{{ $errors->first('phone') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <strong>Subject:</strong>
                                        <input type="text" name="subject" class="form-control" placeholder="Subject" value="{{ old('subject') }}">
                                        @if ($errors->has('subject'))
                                            <span class="text-danger">{{ $errors->first('subject') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <strong>Message:</strong>
                                        <textarea name="message" rows="3" class="form-control">{{ old('message') }}</textarea>
                                        @if ($errors->has('message'))
                                            <span class="text-danger">{{ $errors->first('message') }}</span>
                                        @endif
                                    </div>  
                                </div>
                            </div>

                            <div class="form-group text-center">
                                <button class="btn btn-success btn-submit">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/contactMail.blade.php
<h2>Hey !</h2> <br><br>

You received an email from : {{ $name }} <br><br>

User details: <br><br>

Name:  {{ $name }}<br>
Email:  {{ $email }}<br>
Phone:  {{ $phone }}<br>
Subject:  {{ $subject }}<br>
Message:  {!! $subject !!}<br><br>

Thanks

resources/views/index.blade.php
@extends('layouts.main')

@section('title', $title)

@section('container')
    <div class="container">
        <h1>{{ $content }}</h1>
    </div>
        
    <div id="Index"></div>
@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link rel="shortcut icon" href="{{ asset('img/favicon.jpg') }}" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- CSS style -->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>
<body>
    @include('partials.navbar')

    @yield('container')

    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Javascript script -->
    <script src="js/script.js"></script>

    <!-- Javascript React -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Rheks</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{ url('/') }}" class="nav-link active" aria-current="page">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url('/about') }}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url('/pemakai') }}" class="nav-link">Pemakai</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url('/stu') }}" class="nav-link">Stu</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link disabled" tabindex="-1" aria-disabled="true">Disabled</a>
                </li> -->
            </ul>
        </div>
    </div>
</nav>

resources/views/pemakai.blade.php
@extends('layouts.main')

@section('title', 'Pemakai | Official Latihan 1')
    
@section('container')
    <div class="container">
        {{-- {{ dd($data[1]["title"]); }} --}}
        @foreach ($data as $d)
            <h1>Judul : {{ $d["title"] }}</h1>
            <h3>Author : {{ $d["author"] }}</h3>
            <p>{{ $d["teks"] }}</p>    
        @endforeach
    </div>
@endsection

resources/views/stu/Create.blade.php
@extends('layouts.main')

@section('title', 'Tambah | Official Latihan 1')

@section('container')
    <div class="container mt-5">
        <h3>Penambahan Konten Stu</h3>
        <form action="/stu" method="POST">
            @csrf
            <div class="mb-3">
                <label for="judul" class="form-label">Judul</label>
                <input type="text" class="form-control @error('judul') is-invalid @enderror" value="{{old('judul')}}" id="judul" name="judul">
                @error('judul')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="penulis" class="form-label">Penulis</label>
                <input type="text" class="form-control" id="penulis" name="penulis" value="{{old('penulis')}}">
            </div>
            <div class="mb-3">
                <label for="teks" class="form-label">Teks</label>
                <input type="text" class="form-control" id="teks" name="teks" value="{{old('teks')}}">
            </div>
            {{-- <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div> --}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/stu/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit | Official Latihan 1')
    
@section('container')
    <div class="container mt-5">
        <h3>Pengubahan Konten Stu</h3>
        <form action="{{ route('stu.update', $stu->id) }}" method="POST">
            @csrf
            @method('patch')
            <div class="mb-3">
                <label for="judul" class="form-label">Judul</label>
                <input type="text" class="form-control @error('judul') is-invalid @enderror" value="{{ $stu->judul }}" id="judul" name="judul">
                @error('judul')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="penulis" class="form-label">Penulis</label>
                <input type="text" class="form-control" id="penulis" name="penulis" value="{{ $stu->penulis }}">
            </div>
            <div class="mb-3">
                <label for="teks" class="form-label">Teks</label>
                <input type="text" class="form-control" id="teks" name="teks" value="{{ $stu->teks }}">
            </div>
            {{-- <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div> --}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/stu/index.blade.php
@extends('layouts.main')

@section('title', 'Stu | Official Latihan 1')

@section('container')
    {{-- @dd($data); --}}

    <div class="container mt-5">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <a href="/stu/create" class="btn btn-primary">Tambah Data Blog</a>
        @foreach ($data as $d)
            <h1>Judul : {{ $d->judul }}</h1>
            <h3>Penulis : {{ $d->penulis }}</h3>
            <p>{{ \Str::limit($d->teks, 100) }}</p>
            
            <form action="{{ route('stu.destroy', $d->id) }}" method="post">
                <a href="{{ route('stu.show', $d->id) }}" class="btn btn-primary">Detail</a>
            <a href="{{ route('stu.edit', $d->id) }}" class="btn btn-success">Edit</a>
                @csrf
                @method('delete')
                <input value="Hapus" type="submit" class="btn btn-danger">
            </form>
        @endforeach
    </div>
@endsection

resources/views/stu/show.blade.php
@extends('layouts.main')

@section('title', 'Show | Official Latihan 1')

@section('container')
    <div class="container">
        <a href="{{ route('stu.index') }}">Back</a>
        <h1>Judul : {{ $stu->judul }}</h1>
        <h3>Penulis : {{ $stu->penulis }}</h3>
        <p>{{ $stu->teks }}</p>
    </div>
@endsection